geolocation_map_provider:
  type: mapping
  mapping:
    map_features:
      type: sequence
      label: 'Map feature settings'
      sequence:
        type: plugin.plugin_configuration.geolocation.map_feature.[%key]
        label: 'The settings for a map feature'


geolocation.map_provider.*:
  type: geolocation_map_provider
  label: 'Empty map provider'

geolocation.map_feature_settings:
  type: mapping
  label: 'Default processor configuration'
  mapping:
    enabled:
      type: integer
      label: 'Enabled yes/no/maybe'

plugin.plugin_configuration.geolocation.map_feature.*:
  type: geolocation.map_feature_settings