geolocation_google_maps.settings:
  type: config_object
  label: 'Geolocation settings'
  mapping:
    google_map_api_key:
      type: string
      label: 'Google Maps API Key'
    google_map_api_server_key:
      type: string
      label: 'Google Maps API Key'
    google_map_custom_url_parameters:
      type: mapping
      label: 'Additional Google Maps API parameters'
      mapping:
        region:
          type: string
          label: 'Region'
        language:
          type: string
          label: 'languae'
        v:
          type: string
          label: 'Version'
        client:
          type: string
          label: 'Client ID'
        libraries:
          type: sequence
          label: 'Libraries'
          sequence:
            type: string
            label: 'Library name'

views.style.maps_common:
  type: geolocation_views_style
  label: 'Geolocation CommonMap'
  mapping:
    google_map_settings:
      type: geolocation.map_provider.google_maps
      label: 'Google Map settings'

geolocation.map_provider.google_maps:
  type: geolocation_map_provider
  label: 'Google Map settings'
  mapping:
    type:
      type: string
      label: 'Google map type'
    zoom:
      type: string
      label: 'Zoom level'
    minZoom:
      type: string
      label: 'Min Zoom'
    maxZoom:
      type: string
      label: 'Max Zoom'
    rotateControl:
      type: integer
      label: 'The state of the rotate control'
    mapTypeControl:
      type: integer
      label: 'Map controls'
    streetViewControl:
      type: integer
      label: 'Street view'
    zoomControl:
      type: integer
      label: 'Zoom control'
    fullscreenControl:
      type: integer
      label: 'The state of the fullscreen control'
    scrollwheel:
      type: integer
      label: 'Scrool wheel'
    disableDoubleClickZoom:
      type: integer
      label: 'Disable double click zoom'
    draggable:
      type: integer
      label: 'Draggable'
    height:
      type: string
      label: 'Height value'
    width:
      type: string
      label: 'Width value'
    info_auto_display:
      type: integer
      label: 'Display info'
    disableAutoPan:
      type: integer
      label: 'Disable automatic panning for info window'
    style:
      type: string
      label: 'JSON encoded style'
    preferScrollingToZooming:
      type: integer
      label: 'Require user to click map before zooming'
    gestureHandling:
      type: string
      label: 'Smart scrolling'
